import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_csv("medicine.csv")
df=df.dropna(subset=["prescription_required"])
brand_count = df["brand_name"].value_counts()
plt.figure(figsize=(10,6))
plt.pie(brand_count.values, labels=brand_count.index, autopct='%1.1f%%')
plt.title("Count of Brands")
plt.xlabel("Brand")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.savefig("brand_count_pie_chart.png")
plt.show()

stock_range=df["stock"].max() - df["stock"].min()
plt.hist(df["stock"], bins=20, edgecolor='black')
plt.title("Distribution of Stock")
plt.xlabel("Stock")
plt.ylabel("Frequency")
plt.grid(axis='y')
plt.show()

price_scattered=df[["price_inr", "stock"]].dropna()
plt.scatter(price_scattered["price_inr"], price_scattered["stock"], alpha=0.5)
plt.title("Price vs Stock")
plt.xlabel("Price")
plt.ylabel("Stock")
plt.grid()
plt.show()
